## Settings
title: DoDataScience
owner: "Towaha"
url: "https://dodatascience.co.uk"
baseurl: "/dodatascience.github.io"
permalink: /:title/
description: "DoDataScience"
markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
email: "DoDataScienceUk@gmail.com"
github: "dodatascience/dodatascience.github.io"
# path to: css/, fonts/, img/ and js/
assets_path: "/assets" # i.e. "/assets" 
statement: "Lets see what comes next!"
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 3
# texts randomly displayed in background
bgtext: "αβγδεζηθικλμνξοπρστυφχψω∷∫∮∝∞∧∨∑∏∪∩∈∵∴⊥‖∠⌒⊙≌√"
